# This template is heavily inspired by the shadcn-ui/ui repository.
# See: https://github.com/shadcn-ui/ui/blob/main/.github/ISSUE_TEMPLATE/config.yml

blank_issues_enabled: false
contact_links:
  - name: 🙋 Question or getting started?
    about: Ask a question or get help with using the components.
    url: https://github.com/tobidsn/acfui/discussions?category=general
