// @ts-nocheck
// This file is autogenerated by scripts/build-registry.ts
// Do not edit this file directly.
import * as React from "react"

export const Index: Record<string, any> = {
  "default": {
    "camera": {
      name: "camera",
      description: "",
      type: "registry:ui",
      registryDependencies: ["button"],
      files: [{
        path: "registry/default/ui/camera.tsx",
        type: "registry:ui",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/ui/camera.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "post-object": {
      name: "post-object",
      description: "",
      type: "registry:ui",
      registryDependencies: ["badge","button","popover","command","select"],
      files: [{
        path: "registry/default/ui/post-object.tsx",
        type: "registry:ui",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/ui/post-object.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "relationship": {
      name: "relationship",
      description: "",
      type: "registry:ui",
      registryDependencies: ["badge","button","input","select","card"],
      files: [{
        path: "registry/default/ui/relationship.tsx",
        type: "registry:ui",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/ui/relationship.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "table-field": {
      name: "table-field",
      description: "",
      type: "registry:ui",
      registryDependencies: ["button","input"],
      files: [{
        path: "registry/default/ui/table-field.tsx",
        type: "registry:ui",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/ui/table-field.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "one-click-blog-post": {
      name: "one-click-blog-post",
      description: "",
      type: "registry:ui",
      registryDependencies: ["button","input","card","label","tooltip"],
      files: [{
        path: "registry/default/ui/one-click-blog-post.tsx",
        type: "registry:ui",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/ui/one-click-blog-post.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "utils": {
      name: "utils",
      description: "",
      type: "registry:lib",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/lib/utils.ts",
        type: "registry:lib",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/lib/utils.ts")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "camera-demo": {
      name: "camera-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["camera"],
      files: [{
        path: "registry/default/examples/camera-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/camera-demo.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "camera-mask-square-demo": {
      name: "camera-mask-square-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["camera"],
      files: [{
        path: "registry/default/examples/camera-mask-square-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/camera-mask-square-demo.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "camera-mask-round-demo": {
      name: "camera-mask-round-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["camera"],
      files: [{
        path: "registry/default/examples/camera-mask-round-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/camera-mask-round-demo.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "camera-mask-card-demo": {
      name: "camera-mask-card-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["camera"],
      files: [{
        path: "registry/default/examples/camera-mask-card-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/camera-mask-card-demo.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "camera-manual-control-demo": {
      name: "camera-manual-control-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["camera","button"],
      files: [{
        path: "registry/default/examples/camera-manual-control-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/camera-manual-control-demo.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "camera-custom-capture-demo": {
      name: "camera-custom-capture-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["camera","button"],
      files: [{
        path: "registry/default/examples/camera-custom-capture-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/camera-custom-capture-demo.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "camera-permission-demo": {
      name: "camera-permission-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["camera","button","card","alert","badge","dialog"],
      files: [{
        path: "registry/default/examples/camera-permission-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/camera-permission-demo.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "camera-size-default-demo": {
      name: "camera-size-default-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["camera"],
      files: [{
        path: "registry/default/examples/camera-size-default-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/camera-size-default-demo.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "camera-size-small-demo": {
      name: "camera-size-small-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["camera"],
      files: [{
        path: "registry/default/examples/camera-size-small-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/camera-size-small-demo.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "camera-size-large-demo": {
      name: "camera-size-large-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["camera"],
      files: [{
        path: "registry/default/examples/camera-size-large-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/camera-size-large-demo.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "camera-size-xl-demo": {
      name: "camera-size-xl-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["camera"],
      files: [{
        path: "registry/default/examples/camera-size-xl-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/camera-size-xl-demo.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "camera-aspect-4-3-demo": {
      name: "camera-aspect-4-3-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["camera"],
      files: [{
        path: "registry/default/examples/camera-aspect-4-3-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/camera-aspect-4-3-demo.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "camera-aspect-16-9-demo": {
      name: "camera-aspect-16-9-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["camera"],
      files: [{
        path: "registry/default/examples/camera-aspect-16-9-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/camera-aspect-16-9-demo.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "camera-aspect-1-1-demo": {
      name: "camera-aspect-1-1-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["camera"],
      files: [{
        path: "registry/default/examples/camera-aspect-1-1-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/camera-aspect-1-1-demo.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "camera-mirror-false-demo": {
      name: "camera-mirror-false-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["camera"],
      files: [{
        path: "registry/default/examples/camera-mirror-false-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/camera-mirror-false-demo.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "camera-mirror-true-demo": {
      name: "camera-mirror-true-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["camera"],
      files: [{
        path: "registry/default/examples/camera-mirror-true-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/camera-mirror-true-demo.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "camera-mirror-preview-demo": {
      name: "camera-mirror-preview-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["camera"],
      files: [{
        path: "registry/default/examples/camera-mirror-preview-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/camera-mirror-preview-demo.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "post-object-demo": {
      name: "post-object-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["post-object","badge","button","popover","command","select"],
      files: [{
        path: "registry/default/examples/post-object-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/post-object-demo.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "post-object-multiple-demo": {
      name: "post-object-multiple-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["post-object","badge","button","popover","command","select"],
      files: [{
        path: "registry/default/examples/post-object-multiple-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/post-object-multiple-demo.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "post-object-async-demo": {
      name: "post-object-async-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["post-object","badge","button","popover","command","select"],
      files: [{
        path: "registry/default/examples/post-object-async-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/post-object-async-demo.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "relationship-demo": {
      name: "relationship-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["relationship","badge","button","input","select"],
      files: [{
        path: "registry/default/examples/relationship-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/relationship-demo.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "relationship-single-demo": {
      name: "relationship-single-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["relationship","badge","button","input","select","card"],
      files: [{
        path: "registry/default/examples/relationship-single-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/relationship-single-demo.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "relationship-async-demo": {
      name: "relationship-async-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["relationship","badge","button","input","select"],
      files: [{
        path: "registry/default/examples/relationship-async-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/relationship-async-demo.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "relationship-advanced-demo": {
      name: "relationship-advanced-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["relationship","badge","button","input","select","card","switch","label","tabs"],
      files: [{
        path: "registry/default/examples/relationship-advanced-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/relationship-advanced-demo.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "table-field-demo": {
      name: "table-field-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["table-field","button","input"],
      files: [{
        path: "registry/default/examples/table-field-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/table-field-demo.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "table-field-add-column-demo": {
      name: "table-field-add-column-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["table-field","button","input"],
      files: [{
        path: "registry/default/examples/table-field-add-column-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/table-field-add-column-demo.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "table-field-add-row-demo": {
      name: "table-field-add-row-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["table-field","button","input"],
      files: [{
        path: "registry/default/examples/table-field-add-row-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/table-field-add-row-demo.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "table-field-dynamic-demo": {
      name: "table-field-dynamic-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["table-field","button","input"],
      files: [{
        path: "registry/default/examples/table-field-dynamic-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/table-field-dynamic-demo.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "one-click-blog-post-demo": {
      name: "one-click-blog-post-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["one-click-blog-post"],
      files: [{
        path: "registry/default/examples/one-click-blog-post-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/one-click-blog-post-demo.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
  },
}
